name: CI
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get Golang dependencies
      run: |
        go get -v -t -d ./...
    - name: Run Golang code vetting
      run: make vet
    - name: Run Golang code vetting
      run: make test
    - name: Build
      run: go build -v -o ramsql main.go
