name: CI
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Golang dependencies
      run: |
        go get -v -t -d ./...
    - name: Run code vet
      run: make vet
    - name: Run code tests
      run: make test test-coverage
    - name: Run code build
      run: make build
